import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";
import clsx from 'clsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from '@/components/ui/ThemeProvider';
import { Header } from '@/components/layout/Header';
import { BottomNav } from '@/components/layout/BottomNav';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={clsx('flex', 'flex-col', 'bg-slate-50', 'dark:bg-slate-950', 'min-h-full', 'text-slate-900', 'dark:text-slate-100', 'transition-colors', 'duration-200')}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className={clsx('flex-grow', 'mx-auto', 'px-4', 'py-8', 'pb-24', 'md:pb-8', 'container')}>
            {children}
          </main>
          <BottomNav />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
